services:
  - type: web
    name: student-portfolio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CLOUDINARY_URL
        sync: false   # Set in Render Dashboard
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /mnt/data
      sizeGB: 1
