services:
  - type: web
    name: student-portfolio
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CLOUDINARY_URL
        sync: false  # Add in Render dashboard for security
      - key: SECRET_KEY
        sync: false  # Flask secret key
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1
